// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Kn1LNr94HPrUY0MHOPUO6nqHgmFyCw4',
    appId: '1:357724777280:web:36066947bf025172ace8a5',
    messagingSenderId: '357724777280',
    projectId: 'project2-43d8b',
    authDomain: 'project2-43d8b.firebaseapp.com',
    storageBucket: 'project2-43d8b.firebasestorage.app',
    measurementId: 'G-FPERSL5W4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlA7UUCdsOIPoRlW6BtiOt6baf0RYxcE',
    appId: '1:357724777280:android:94acc102460693abace8a5',
    messagingSenderId: '357724777280',
    projectId: 'project2-43d8b',
    storageBucket: 'project2-43d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JXTw0eNgPp1Tw6mX1nvW3UvQtvcrDbA',
    appId: '1:357724777280:ios:0567a46585182683ace8a5',
    messagingSenderId: '357724777280',
    projectId: 'project2-43d8b',
    storageBucket: 'project2-43d8b.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7JXTw0eNgPp1Tw6mX1nvW3UvQtvcrDbA',
    appId: '1:357724777280:ios:0567a46585182683ace8a5',
    messagingSenderId: '357724777280',
    projectId: 'project2-43d8b',
    storageBucket: 'project2-43d8b.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Kn1LNr94HPrUY0MHOPUO6nqHgmFyCw4',
    appId: '1:357724777280:web:478c88bad927e205ace8a5',
    messagingSenderId: '357724777280',
    projectId: 'project2-43d8b',
    authDomain: 'project2-43d8b.firebaseapp.com',
    storageBucket: 'project2-43d8b.firebasestorage.app',
    measurementId: 'G-S35M8XNRD7',
  );
}
